In [3]:
import numpy as np

x = np.eye(10)
x[1] = 1
print(x)

[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]]


In [4]:
y = np.dot(x[1],x[1].T)
print(y)

10.0


In [5]:
a = np.array([3,1,2,6,2,9,0,-2,3])
print a, np.size(a)

[ 3  1  2  6  2  9  0 -2  3] 9


In [6]:
print a[np.argsort(a)[:3]]

[-2  0  1]


In [7]:
b = np.array([1,3])
a[b]

array([1, 6])

In [8]:
closest_y = np.array([1,8,2,3,3,2,3])

max_votes = 0
winner    = 10 # max label + 1
for c in closest_y:
    votes = np.sum(c == closest_y)
    print(c,votes)
    if (votes > max_votes) or (votes == max_votes and c < winner):
        winner = c
        max_votes = votes
        print('updated winner to ' + str(winner))

(1, 1)
updated winner to 1
(8, 1)
(2, 2)
updated winner to 2
(3, 3)
updated winner to 3
(3, 3)
(2, 2)
(3, 3)


In [9]:
x = np.array([[1,2,3,4],[0,1,0,0]])
print(x.shape)

xx = x.reshape((2,4,1))
print(xx.shape)

y = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
print(y.shape)

yy = y.T.reshape((1,4,3))
print(yy.shape)
print

np.sum((xx-yy)**2,axis=1)

(2, 4)
(2, 4, 1)
(3, 4)
(1, 4, 3)



array([[14,  6,  6],
       [ 3, 13, 31]])

In [10]:
A = np.diag(np.dot(x,x.T))
B = np.diag(np.dot(y,y.T))
C = np.dot(x,y.T)

A = A.reshape((2,1))
B = B.reshape((1,3))
print(np.shape(A))
print(np.shape(B))
print(np.shape(C))

A + B - 2*C

(2, 1)
(1, 3)
(2, 3)


array([[14,  6,  6],
       [ 3, 13, 31]])

In [11]:
x = np.arange(10)
print(x)
print(np.array_split(x,2))

y = np.array_split(x,2)
print(type(y[1]))

z = np.array(y)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]
<type 'numpy.ndarray'>
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
for cnt in range(5):
    print(cnt)

0
1
2
3
4


In [13]:
n = 5
for i in np.arange(5):
    print(i)
    print(np.concatenate((np.arange(0,i),np.arange(i+1,n)),axis=0))

0
[1 2 3 4]
1
[0 2 3 4]
2
[0 1 3 4]
3
[0 1 2 4]
4
[0 1 2 3]


In [14]:
x = np.array([1,2,3])
x.shape
print(x[1:])

a = np.zeros(3)
a
for cnt,i in enumerate(range(3)):
    a[cnt] = i-10
print(a)

[2 3]
[-10.  -9.  -8.]


In [15]:
A = np.array([[1,2,3],[0,1,0]])
B = np.zeros(A.shape)
print(B)
B[np.nonzero(A)] = 1
print(B)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 0.  1.  0.]]


In [18]:
learningrate = np.logspace(-3,-1,num=3)
learningrate

array([ 0.001,  0.01 ,  0.1  ])